baseURL = "https://minlno.github.io"
languageCode = "en-US"
title = "Minho Kim"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "images/JJang.jpg"
  author = "Minho Kim"
  description = "Minho Kim's Website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/style.css"]
  custom_js  = []

[params.social]
  Github        = "minlno"
  Email         = "minho7571@gmail.com"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
