baseURL = 'http://minlno.github.io/'
languageCode = 'en-us'
theme = 'hugo-xmin'
enableEmoji = true

[params]
author = "Minho Kim"

color = 'linen'

github = 'minlno'
rss = true

name = 'Minho Kim'

disableHLJS = true
disablePostNavigation = true
monoDarkIcon = true
math = true
localKatex = false

[taxonomies]
  category = "categories"
  tag = "tags"
